project:
  type: website
  output-dir: docs

website:
  title: "KNN Diabetes Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Paper

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    code-fold: false
